### PR TITLE
added how to manually update application

### PR DESCRIPTION
**Pull request by jacobped**
Just so it's there for people like me, who have no idea how to update it when you release a new version.

### CODE REVIEW

**Comment by twolfson** [comment]
Ah, nice. I would prefer to define this in another section but I will definitely land it.

Also, for what it's worth; it's typically a good practice to use the `@latest` tag as well to ensure an upgrade occurs:

``` bash
npm install -g google-music-electron@latest
```

**Comment by twolfson** [comment]
Ah, nvm. I misread your commit as `install` -- yep, `update` should work as well =)

**Comment by jacobped** [comment]
Moved it and changed it so is follows same "design" as the getting started part

**Comment by twolfson** [comment]
Added a few personal touches (e.g. removed redundant words, changed tense of "Update"). This has been merged/released in `1.14.1`. Thanks for the PR =)

**Pull request merged**
